# Site settings
title: acroos
email: me@acroos.site
description: > 
  human
baseurl: 
url:  http://acroos.github.io
twitter_username: __acroos
github_username:  acroos

# Build settings
markdown: kramdown

highlighter: rouge
plugins: 
  - jekyll-paginate

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /project/:path/