#!/bin/sh

if [[ $# -eq 0 ]]; then
  echo "No post name given, exiting..."
  exit 1
fi

TITLE="$@"
TODAY=`date +"%Y-%m-%d"`
FILENAME="${TODAY}-${TITLE// /-}.md"
FILEPATH="$(dirname $(dirname $0))/_posts/${FILENAME}"

echo """---
layout: post
title:  '${TITLE}'
date:   ${TODAY}
---
""" > $FILEPATH
