#!/bin/sh

TITLE="$@"
TODAY=`date +"%Y-%m-%d"`
FILENAME="${TODAY}-${TITLE// /-}.md"
FILEPATH="$(dirname $(dirname $0))/_posts/${FILENAME}"

echo """---
layout: post
title:  '${TITLE}'
date:   ${TODAY}
---
""" > $FILEPATH